Snitch enum
SoPra-Team-10/GameLogic pull request #101
Opened 2019-05-08 16:43 UTC by pmo73

2019-05-08 16:44 UTC, pmo73 commented
Der geht noch auf den Master, konnte Develop nicht auswählen, habe verkackt oder den gibt es nicht?

2019-05-09 11:43 UTC, Timmifixedit requested changes

2019-05-09 11:43 UTC, Timmifixedit commented on GameController.cpp
> +                throw std::runtime_error("Snitch does not exist");
snitch exists nur einmal prüfen

2019-05-09 11:43 UTC, Timmifixedit commented on GameController.cpp
> +                if(getDistance(pos, gameModel::Position{8,6}) < minDistanceMiddle){
getCrossedCells[0] ist die Zelle in die du laufen möchtests

2019-05-09 11:43 UTC, Timmifixedit commented on GameModel.h
> +        Normal,
Enum name: ExcessLength, Stage1, 2 ....

2019-05-09 13:53 UTC, jonas-merkle reviewed
same as Tim

2019-05-09 16:06 UTC, Timmifixedit approved these changes

2019-05-09 16:11 UTC, jonas-merkle approved these changes

2019-05-09 16:30 UTC, jonas-merkle requested changes
Bidde seg fault beheben -> siehe CI (docker exited with 139)

2019-05-09 17:17 UTC, jonas-merkle approved these changes

2019-05-09 17:21 UTC, merged