Develop
SoPra-Team-10/GameLogic pull request #108
Opened 2019-05-09 16:51 UTC by Timmifixedit

2019-05-09 19:01 UTC, aul12 requested changes

2019-05-09 19:01 UTC, aul12 commented on GameController.cpp
> +                auto disnatceTeam2 = getDistance(snitch->position, env->team2->seeker->position);
typo

2019-05-09 19:01 UTC, aul12 commented on GameModel.h
> +        Snitch(Position position);
Wieso explicit weg?

2019-05-09 19:01 UTC, aul12 commented on GameModel.h
> +        static bool checkTeamConfig(const communication::messages::request::TeamConfig &config);
Hierzu gibt es keine Implementierung...

2019-05-09 19:01 UTC, aul12 commented on GameModel.h
> +        static bool checkTeamFormation(const communication::messages::request::TeamFormation &formation);
Ebenfalls

2019-05-09 20:15 UTC, Timmifixedit commented on GameModel.h
> +        static bool checkTeamConfig(const communication::messages::request::TeamConfig &config);
@pmo73 @jonas-merkle Wo ist die Implementierung hin? Ist die im Server?

2019-05-10 08:24 UTC, jonas-merkle commented on GameModel.h
> +        static bool checkTeamConfig(const communication::messages::request::TeamConfig &config);
ja die ist im Server ... ich nehm des hier raus...

2019-05-10 08:42 UTC, jonas-merkle approved these changes

2019-05-10 08:42 UTC, aul12 approved these changes

2019-05-10 08:48 UTC, merged