fixed #128
SoPra-Team-10/GameLogic pull request #131
Opened 2019-05-21 15:50 UTC by jonas-merkle

2019-05-21 16:25 UTC, pmo73 approved these changes

2019-05-21 16:47 UTC, Timmifixedit requested changes

2019-05-21 16:47 UTC, Timmifixedit commented on GameController.cpp
> +        auto minDistancePlayer = minDistancePlayers[rng(0, (int) minDistancePlayers.size() - 1)];
static cast

2019-05-21 16:47 UTC, Timmifixedit commented on GameController.cpp
> +                    minDistancePlayers.emplace_back(player);
Das funzt glaub so nicht. Den ersten Spieler, der kein Beater ist, fügst du immer hinzu, egal, wie weit der weg ist. Der wird ja zumindest weniger weit weg sein, als der größte int

2019-05-22 10:01 UTC, Timmifixedit approved these changes

2019-05-22 10:01 UTC, merged