Sonarcloud integration
SoPra-Team-10/GameLogic pull request #161
Opened 2019-05-28 18:54 UTC by jonas-merkle

2019-05-28 19:31 UTC, Timmifixedit approved these changes

2019-05-28 19:31 UTC, Timmifixedit commented on src/GameController.h
>  #include "GameModel.h"
Muss das nicht auch im src sein??

2019-05-28 19:38 UTC, aul12 requested changes

2019-05-28 19:38 UTC, aul12 commented on Dockerfile
> +#CMD ["build/Tests/Tests", "--gtest_repeat=10", "--gtest_shuffle", "--gtest_color=yes"]
Willst du den nicht als Standard CMD drinnen lassen?

2019-05-28 19:38 UTC, aul12 commented on Dockerfile
> +RUN apt-get update -y && apt-get install -y libgtest-dev cmake gcc-8 g++-8 libasan5 google-mock git wget unzip bash
Ist es nicht möglich die Dependencies erst nachher im script zu installieren? Dann ist das Dockerfile unabhängig von SonarQube

2019-05-28 19:41 UTC, aul12 commented
Außerdem wäre ein Link zu der Sonarqube seite im README ganz nett

2019-05-28 20:07 UTC, aul12 commented
Gleiche Anmerkung, da ist immer noch Sonarqube zeugs im Dockerfile.  Und den auskommentierten CMD kannst du auch rausnehmen

2019-05-28 20:59 UTC, aul12 approved these changes

2019-05-28 21:05 UTC, aul12 requested changes
Schau ich mir morgen auch nochmal wegen includes an

2019-05-29 08:32 UTC, aul12 approved these changes

2019-05-29 09:16 UTC, merged