fixes, die von sonarqube vorgeschlagen wurden
SoPra-Team-10/GameLogic pull request #177
Opened 2019-06-07 09:07 UTC by jonas-merkle

2019-06-07 13:04 UTC, aul12 requested changes

2019-06-07 13:04 UTC, aul12 commented on src/Action.cpp
> +        if(env->snitch->exists && this->env->snitch->position == this->target && INSTANCE_OF(this->actor, gameModel::Seeker)
Vielleicht mit ein paar kleinen Hilfsvariableb
```suggestion
        const bool positionIsTarget = this->env->snitch->position == this->target;
        const bool isSeeker =  INSTANCE_OF(this->actor, gameModel::Seeker);
        const bool actionTriggered = actionTriggered(env->config.gameDynamicsProbs.catchSnitch);
        if(env->snitch->exists && positionIsTarget  && isSeeker && actionTriggered) {
```

2019-06-07 13:04 UTC, aul12 commented on src/GameController.h
> +constexpr int GOAL_POINTS = 10;
Muss das im Header definiert sein (und auch noch außerhalb jeden Namespaces?)?

2019-06-07 13:04 UTC, aul12 commented on src/Interference.cpp
> +        return Interference::isPossible() && gameModel::Environment::getCell(target->position) != gameModel::Cell::OutOfBounds;
Hilfsvariablen oder zumindest in mehrere Zeilen aufteilen

2019-06-07 13:04 UTC, aul12 commented on src/Interference.cpp
> +        return Interference::isPossible() && !team->hasMember(target) && gameModel::Environment::getCell(target->position) != gameModel::Cell::OutOfBounds;
Ebenfalls

2019-06-07 13:04 UTC, aul12 commented on src/Interference.cpp
> +        return Interference::isPossible() && Interference::env->cellIsFree(target) && !env->isShitOnCell(target) && gameModel::Environment::getCell(target) != gameModel::Cell::OutOfBounds;
Auch

2019-06-07 13:04 UTC, aul12 commented on src/GameController.cpp
> +        while((notOutOfBounds1 = gameModel::Environment::getCell(lowerCell.x + static_cast<int>(std::round(dirVectOrtho.x)), lowerCell.y + static_cast<int>(std::round(dirVectOrtho.y))) != gameModel::
Geht das nicht ohne sideeffekts in der Bedinung?

2019-06-08 15:14 UTC, Timmifixedit commented on src/GameController.h
> +constexpr int GOAL_POINTS = 10;
Im Header wäre gut, weil wir das dann auch Im Server usw nuttzen können. Aber bittte im namespace

2019-06-08 15:16 UTC, Timmifixedit approved these changes
Ich schließe mich Pauls Kritik an, approve aber schon mal.

2019-06-11 11:07 UTC, aul12 requested changes

2019-06-11 11:07 UTC, aul12 commented on src/Action.h
> +        ~Action() = default;
```suggestion
        virtual ~Action() = default;
```

2019-06-11 11:07 UTC, aul12 commented on src/Action.cpp
> +            if(gameModel::Environment::isGoalCell(target) && playerOnTarget.has_value() && !env->arePlayerInSameTeam(actor, playerOnTarget.value())){
Auteilen, hilfsvariablen oder so

2019-06-11 11:07 UTC, aul12 commented on src/Action.cpp
> +        if ((env->team1->hasMember(this->actor) && gameModel::Environment::getCell(this->target) == gameModel::Cell::GoalLeft) ||
Auch

2019-06-11 11:07 UTC, aul12 commented on src/Action.cpp
> +            if (env->quaffle->position == this->actor->position &&
Auch

2019-06-11 11:49 UTC, aul12 approved these changes

2019-06-11 12:02 UTC, merged