getLegalCellsAround implementiert
SoPra-Team-10/GameLogic pull request #189
Opened 2019-06-16 17:24 UTC by Timmifixedit

2019-06-17 05:57 UTC, jonas-merkle requested changes
Ich versteh den Sinn von leftTeam nicht so ganz. Geht das nicht ohne diesen Umschalter?

2019-06-17 07:57 UTC, Timmifixedit commented
@jonas-merkle LeftTeam brauchst du, damit du überprüfen kannst, ob du auf die goalCell drauf darfst oder nicht.

2019-06-17 08:04 UTC, aul12 requested changes

2019-06-17 08:04 UTC, aul12 commented on Tests/Model.cpp
> +    EXPECT_EQ(res[0], gameModel::Position(0, 7));
Was wenn sich reihenfolge der Zellen ändert, kein Teil der Anforderung, dass genau die Reihenfolge

2019-06-18 11:07 UTC, aul12 approved these changes

2019-06-18 14:48 UTC, merged