get all Actions
SoPra-Team-10/GameLogic pull request #195
Opened 2019-06-21 16:31 UTC by Timmifixedit

2019-06-21 18:30 UTC, aul12 requested changes

2019-06-21 18:30 UTC, aul12 commented on Tests/Controller.cpp
> +        EXPECT_NE(move.check(), gameController::ActionCheckResult::Impossible);
Vielleicht noch checken ob auch Nachbar Zellen und unique?

2019-06-21 18:30 UTC, aul12 commented on Tests/Controller.cpp
> +    auto moves = gameController::getAllPossibleShots(env->team1->beaters[0], env, 0);
Sollte besser `shots` heißen

2019-06-22 10:36 UTC, Timmifixedit commented on Tests/Controller.cpp
> +        EXPECT_NE(move.check(), gameController::ActionCheckResult::Impossible);
ist nicht ohne weiters Möglich, da Move.target private ist. Außerdem überprüft Move schon, ob der Move nur eine Zelle weit geht. Uniqueness kann ich wegen private member nicht prüfen

2019-06-22 14:43 UTC, Timmifixedit commented on Tests/Controller.cpp
> +        EXPECT_NE(move.check(), gameController::ActionCheckResult::Impossible);
habs jetzt public gemacht

2019-06-22 14:50 UTC, aul12 commented on Tests/Controller.cpp
> +        EXPECT_NE(move.check(), gameController::ActionCheckResult::Impossible);
Was spricht gegen einen getter?

2019-06-22 14:51 UTC, aul12 approved these changes

2019-06-23 07:44 UTC, merged