Develop
SoPra-Team-10/GameLogic pull request #24
Opened 2019-05-03 12:25 UTC by aul12

2019-05-03 19:46 UTC, Timmifixedit requested changes

2019-05-03 19:46 UTC, Timmifixedit commented on GameController.h
> +     * Generates a random integer in [min, max)
Doku anpassen

2019-05-03 19:46 UTC, Timmifixedit commented on GameModel.cpp
> +                    if (Environment::getCell(j, i) != Cell::OutOfBounds && this->getPlayer(Position(j, i)) == nullptr) {
has_value wäre doch besser

2019-05-03 21:02 UTC, jonas-merkle approved these changes

2019-05-04 10:52 UTC, Timmifixedit approved these changes

2019-05-04 11:27 UTC, jonas-merkle approved these changes

2019-05-04 11:27 UTC, merged